export const jobTitles = [
  "Interdimensional Scientist",
  "Portal Gun Maintenance Technician",
  "Squanch Interpreter",
  "Plumbus Quality Control Inspector",
  "Meeseeks Box Operator",
  "Cronenberg Containment Specialist",
  "Galactic Federation Fugitive",
  "Pickle Rick Emergency Responder",
  "Gazorpazorp Culture Consultant",
  "Bird Person Translation Services",
  "Unity Hive Mind Coordinator",
  "Schwifty Dance Instructor",
  "Jerry Daycare Supervisor",
  "Tiny Rick Babysitter",
  "Wubba Lubba Dub Dub Therapist",
  "Citadel of Ricks Security Guard",
  "Evil Morty Campaign Manager",
  "Schmeckle Exchange Specialist",
  "Peace Among Worlds Diplomat",
  "Get Schwifty Talent Scout",
];
